FROM docker.for.mac.localhost:5001/gladsheim/alpine:withtz
EXPOSE {{ cookiecutter.port }}

ENV GODEBUG=netdns=go

ADD release/{{ cookiecutter.project_slug }} /bin
ADD conf/config.dev.json /bin/{{ cookiecutter.project_slug }}.json

ENTRYPOINT ["/bin/{{ cookiecutter.project_slug }}"]
