version: '3'

services:
  {{ cookiecutter.project_slug }}:
    image: registry.cn-hangzhou.aliyuncs.com/gladsheim/{{ cookiecutter.project_slug }}:devel
    volumes:
      - /Users/Odin/logs/go:/logs
    ports:
      - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
    env_file:
      - ./dev.env
